---
title: "WriteUp Linear Model with prediction"
author: "Rita Jarbanda"
date: "2023-11-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(tigerstats)
require(knitr)

data <- read.csv(file="https://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)  

```

## Model 1 SIMS~ARM
### Scarttered Plot



```{r}
basicNN <- ggplot(data,aes(y=SIMS,x=ARM))

```

```{r}
basicNN + geom_point() + ggtitle("SIMS vs ARM") + theme(plot.title = element_text(hjust = 0.5, size = 20))
```


This scatter plot reflects a positive correlation since some of the dots are showing a behavior of going up diagonally. This data shows the simulation expectation of arm strength in the workers. This tells us that it is expected for most of the population to have a strength between 50 to 100 for arm strength. 






























































































































































































